---
# See https://docs.gitlab.com/ee/ci/yaml/README.html

.with_node:
    image: node:18-alpine
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .pnpm-store
    before_script:
        - npm i --location=global pnpm
        - pnpm config set store-dir .pnpm-store

.base_build:
    extends: .with_node
    stage: build
    script:
        - pnpm install
        - pnpm build

.base_pages:
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes:
              - 'CHANGELOG.md'

stages:
    - lint
    - build
    - publish
    - deploy

enable_merge:
    image: alpine:latest
    stage: lint
    rules:
        - if: $CI_MERGE_REQUEST_ID
    script: echo true

lint:
    extends: .with_node
    script: pnpm install && pnpm lint && pnpm check
    stage: lint
    rules:
        - if: $CI_MERGE_REQUEST_ID
          changes:
              - '**/*.cjs'
              - '**/*.html'
              - '**/*.js'
              - '**/*.svelte'
              - '**/*.ts'
              - 'package.json'
              - 'pnpm-lock.yaml'

build_merge_request:
    extends: .base_build
    rules:
        - if: $CI_MERGE_REQUEST_ID
          changes:
              - '.gitlab-ci.yml'
              - '**/*.cjs'
              - '**/*.css'
              - '**/*.html'
              - '**/*.js'
              - '**/*.svelte'
              - '**/*.ts'
              - 'package.json'
              - 'pnpm-lock.yaml'

publish:
    extends: .with_node
    stage: publish
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes:
              - '.changeset/**'
    script: |
        pnpm install
        pnpm changesets-gitlab
    variables:
        INPUT_PUBLISH: pnpm package && pnpm publish package

build_pages:
    extends:
        - .base_build
        - .base_pages
    artifacts:
        paths:
            - build
    variables:
        VITE_BASE: /svelte-location-picker

pages:
    extends: .base_pages
    stage: deploy
    script: mv build public
    artifacts:
        paths:
            - public
    needs:
        - job: build_pages
          artifacts: true
