---
# See https://docs.gitlab.com/ee/ci/yaml/README.html

.with_node:
    image: kucrut/pnpm
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .pnpm-store
    before_script:
        - pnpm config set store-dir .pnpm-store

.base_release:
    extends: .with_node
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes:
              - 'CHANGELOG.md'

variables:
    CHANGESET_RELEASE_BRANCH: changeset-release/main

stages:
    - lint
    - build
    - pre-release
    - release
    - deploy

enable_merge:
    image: alpine:latest
    stage: lint
    rules:
        - if: $CI_MERGE_REQUEST_ID
    script: echo true

lint:
    extends: .with_node
    script: pnpm install && pnpm lint && pnpm check
    stage: lint
    rules:
        - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != $CHANGESET_RELEASE_BRANCH
          changes:
              - '**/*.cjs'
              - '**/*.html'
              - '**/*.js'
              - '**/*.svelte'
              - '**/*.ts'
              - 'package.json'
              - 'pnpm-lock.yaml'

build_merge_request:
    extends: .with_node
    stage: build
    script:
        - pnpm install
        - pnpm build
    rules:
        - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != $CHANGESET_RELEASE_BRANCH
          changes:
              - '.gitlab-ci.yml'
              - '**/*.cjs'
              - '**/*.css'
              - '**/*.html'
              - '**/*.js'
              - '**/*.svelte'
              - '**/*.ts'
              - 'package.json'
              - 'pnpm-lock.yaml'

create_release:
    extends: .with_node
    stage: pre-release
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes:
              - '.changeset/**'
    script: |
        pnpm install
        pnpm changesets-gitlab

release:
    stage: release
    extends: .base_release
    artifacts:
        paths:
            - build
    variables:
        VITE_BASE: /svelte-location-picker
    script: |
        cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
        EOF
        pnpm install
        pnpm build
        pnpm package
        pnpm publish package --access public

pages:
    extends: .base_release
    stage: deploy
    script: mv build public
    artifacts:
        paths:
            - public
    needs:
        - job: release
          artifacts: true
